return {
	PetMutationRegistry = {
		Shocked = {
			EnumId = "a",
			Boosts = {},
			Passives = {"Shocked Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 10,
			Color = Color3.fromRGB(255, 255, 100),
		},
		Golden = {
			EnumId = "b",
			Boosts = {
				{ BoostType = "PASSIVE_BOOST", BoostAmount = 0.1 },
			},
			Passives = {"Golden Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 20,
			Color = Color3.fromRGB(255, 225, 0),
		},
		Rainbow = {
			EnumId = "c",
			Boosts = {
				{ BoostType = "PASSIVE_BOOST", BoostAmount = 0.2 },
			},
			Passives = {"Rainbow Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 10,
			Color = Color3.fromRGB(4, 175, 236),
		},
		Shiny = {
			EnumId = "d",
			Boosts = {
				{ BoostType = "PET_XP_BOOST", BoostAmount = 0.3 },
			},
			Passives = {"Shiny Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 100,
			Color = Color3.fromRGB(145, 207, 221),
		},
		Windy = {
			EnumId = "e",
			Boosts = {},
			Passives = {"Windy Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 30,
			Color = Color3.fromRGB(162, 185, 209),
		},
		Frozen = {
			EnumId = "f",
			Boosts = {{}},
			Passives = {"Frozen Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 30,
			Color = Color3.fromRGB(108, 184, 255),
		},
		Inverted = {
			EnumId = "g",
			Boosts = {
				{ BoostType = "PET_XP_BOOST", BoostAmount = 0.5 },
			},
			Passives = {"Inverted Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 50,
			Color = Color3.fromRGB(128, 128, 128),
		},
		Rideable = {
			EnumId = "h",
			Boosts = {{}},
			Passives = {},
			AvaliableFromMutationMachine = false,
			Chance = 0,
			Color = Color3.fromRGB(255, 255, 255),
		},
		Mega = {
			EnumId = "i",
			Boosts = {
				{ BoostType = "SIZE_MODIFICATION", BoostAmount = 2 },
			},
			Passives = {"Mega Pet Mutation", "Mega Pet Mutation Bonus"},
			AvaliableFromMutationMachine = true,
			Chance = 20,
			Color = Color3.fromRGB(255, 90, 90),
		},
		Tiny = {
			EnumId = "j",
			Boosts = {
				{ BoostType = "SIZE_MODIFICATION", BoostAmount = -0.9 },
			},
			Passives = {"Tiny Pet Mutation", "Tiny Pet Mutation Bonus"},
			AvaliableFromMutationMachine = true,
			Chance = 20,
			Color = Color3.fromRGB(173, 216, 230),
		},
		IronSkin = {
			EnumId = "k",
			Boosts = {{}},
			Passives = {"IronSkin Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 10,
			Color = Color3.fromRGB(206, 206, 206),
		},
		Radiant = {
			EnumId = "l",
			Boosts = {{}},
			Passives = {"Radiant Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 10,
			Color = Color3.fromRGB(248, 108, 38),
		},
		Normal = {
			EnumId = "m",
			Boosts = {},
			Passives = {},
			AvaliableFromMutationMachine = false,
			Color = Color3.fromRGB(255, 255, 255),
		},
		Ascended = {
			EnumId = "n",
			Boosts = {},
			Passives = {"Ascended Pet Mutation"},
			AvaliableFromMutationMachine = true,
			Chance = 1,
			Color = Color3.fromRGB(247, 245, 184),
		},
	}
}
